### PR TITLE
162 modify interdomain broadcast

### LINKED ISSUE #162: Modify adding Inter-Domain Broadcast links results in NullPointerException
Reported by @paul-ruth 

1. Start a new slice with three nodes, in different domains, with _no_ links between them. Create this slice.
1. Modify the slice by adding a _broadcast_ link between two nodes (A and B). Submit this modify.
1. Modify the slice by adding a _broadcast_ link between two nodes (B and C). Submit this modify.
1. `Exception encountered while submitting slice modify request to ORCA: Unable to modify slice: ERROR: ModifySlice Exception!java.lang.NullPointerException`

modifyaddinterdomainbroadcastlink

### PR DESCRIPTION
**Pull request by hinchliff**
Fixes #162, which resulted in an NPE when modifying a slice to add Inter-Domain broadcast links.  

Broadcast VLANs get substituted with multiple links along the path of the interdomain link, and the original VLAN element is 'closed'.  The modify was not ignoring these closed elements, resulting in the NPE.

The change in ModifyHandler is earlier in the call stack.  The follow-on check in InterCloudHandler is thus not strictly necessary, but defensive.

### CODE REVIEW

File: embed/src/main/java/orca/embed/cloudembed/controller/InterCloudHandler.java [hunk 1]
```diff
@@ -139,7 +139,11 @@ else if(domain.equals(RequestReservation.Interdomain_Domain)){  //call @ InterDo
 			s_rr.remove(RequestReservation.MultiPoint_Domain);
             request.getElements().removeAll(mp_elements);
             for(NetworkElement ne:this.mpRequest.getElements()){
-            	//ne.setInDomain(RequestReservation.Interdomain_Domain);
+				// #162 make sure the element has not been Closed before trying to add it
```
Comment (mjstealey) [inline embed/src/main/java/orca/embed/cloudembed/controller/InterCloudHandler.java]: @hinchliff - indentation feels odd here? am I missing something?

Comment (hinchliff) [reply embed/src/main/java/orca/embed/cloudembed/controller/InterCloudHandler.java]: Some of the code is tabs, some of the code is spaces...  (If you view this in an editor with a tab size of 4, it _looks_ right...)

I think the team is in agreement that spaces should be used.  But a lot of the old code still has tabs in it, and we haven't (yet) applied a consistent code style to the project.

**Comment by hinchliff** [comment]
Code formatting / style will be addressed in #168.
